# Generated by Django 5.0.6 on 2024-12-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_contactus_page_remove_home_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentModule',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='FooterModule',
            new_name='Footer',
        ),
        migrations.RenameModel(
            old_name='HeaderModule',
            new_name='Header',
        ),
        migrations.RenameModel(
            old_name='SliderModule',
            new_name='Slider',
        ),
    ]
