# Generated by Django 5.0.6 on 2024-12-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_contentmodule_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageHight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('web', models.ImageField(blank=True, null=True, upload_to='files/hight/images/%Y/%m/%d/')),
                ('mobile', models.ImageField(blank=True, null=True, upload_to='files/hight/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='files/images_Slider/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3498db', max_length=7)),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=7)),
                ('background_color', models.CharField(default='#f5f5f5', max_length=7)),
                ('text_color', models.CharField(default='#333333', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('box_shadow', models.CharField(default='0px 4px 6px rgba(0, 0, 0, 0.1)', max_length=100)),
                ('border_radius', models.CharField(default='5px', max_length=10)),
                ('border_color', models.CharField(default='#dddddd', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='images',
        ),
        migrations.CreateModel(
            name='FrequentlyAsked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freq', to='content.contentfreq')),
            ],
        ),
        migrations.AddField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='content.imageslider'),
        ),
    ]
