# Generated by Django 5.0.6 on 2024-12-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentfreq_imagehight_imageslider_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.frequentlyasked'),
        ),
        migrations.AddField(
            model_name='module',
            name='image_hight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.imagehight'),
        ),
    ]
