# Generated by Django 5.0.6 on 2024-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_module_freq_module_image_hight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('Hight', 'hight'), ('Freq', 'freq'), ('footer', 'Footer')], default='header', max_length=20),
        ),
    ]
