# Generated by Django 5.0.6 on 2024-12-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_module_module_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Freq',
            new_name='freq',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('Hight', 'hight'), ('Freq', 'freq'), ('Youtube', 'youtube'), ('Video', 'video'), ('footer', 'Footer')], default='header', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.videoplayer'),
        ),
        migrations.AddField(
            model_name='module',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.youtubeplayer'),
        ),
    ]
