# Generated by Django 5.0.6 on 2024-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_videoplayer_youtubeplayer_rename_freq_module_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('hight', 'Hight'), ('freq', 'Freq'), ('Youtube', 'youtube'), ('video', 'Video'), ('Footer', 'footer')], default='header', max_length=20),
        ),
    ]
