# Generated by Django 5.0.6 on 2024-12-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_module_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplayer',
            name='is_desktop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='is_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='is_tablet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='themes_desktop_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='themes_mobile_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='themes_tablet_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='is_desktop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='is_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='is_tablet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='themes_desktop_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='themes_mobile_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='youtubeplayer',
            name='themes_tablet_Types',
            field=models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20),
        ),
    ]
