# Generated by Django 5.0.6 on 2024-12-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_videoplayer_is_desktop_videoplayer_is_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='files/Card/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/FeaturesCard/images/%Y/%m/%d/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CountdownBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('date_offer', models.DateField()),
                ('button_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='files/FeaturesCard/images/%Y/%m/%d/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('hight', 'Hight'), ('freq', 'Freq'), ('Youtube', 'youtube'), ('video', 'Video'), ('footer', 'Footer'), ('countdown', 'Countdown'), ('card', 'Card'), ('featuresCard', 'FeaturesCard'), ('features', 'Features')], default='header', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/products/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='module',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.card'),
        ),
        migrations.AddField(
            model_name='module',
            name='countdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.countdownbanner'),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content.contentfeatures')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.features'),
        ),
        migrations.AddField(
            model_name='module',
            name='features_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.featurescard'),
        ),
    ]
