# Generated by Django 5.0.6 on 2024-12-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_module_module_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes_desktop_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_tablet_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('themes_mobile_Types', models.CharField(choices=[('classic', 'Classic'), ('simple', 'Simple'), ('modern', 'Modern')], default='Classic', max_length=20)),
                ('is_mobile', models.BooleanField(default=True)),
                ('is_tablet', models.BooleanField(default=True)),
                ('is_desktop', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='product_grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='content.productgrid'),
        ),
    ]
