# Generated by Django 5.0.6 on 2024-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_productgrid_module_product_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('header', 'Header'), ('slider', 'Slider'), ('content', 'Content'), ('product', 'Product'), ('hight', 'Hight'), ('freq', 'Freq'), ('youtube', 'Youtube'), ('video', 'Video'), ('footer', 'Footer'), ('countdown', 'Countdown'), ('card', 'Card'), ('featurescard', 'FeaturesCard'), ('features', 'Features'), ('productgrid', 'ProductGrid')], default='header', max_length=20),
        ),
    ]
