# Generated by Django 5.0.6 on 2024-12-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_module_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgrid',
            name='page',
            field=models.ManyToManyField(to='content.page'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(to='content.imageslider'),
        ),
    ]
