# Generated by Django 5.0.6 on 2024-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_productgrid_page_alter_slider_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplayer',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
