# Generated by Django 5.0.6 on 2024-12-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_videoplayer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdownbanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='videoplayer',
            name='link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
