# Generated by Django 5.0.6 on 2024-12-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_countdownbanner_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentlyasked',
            name='content',
        ),
        migrations.AddField(
            model_name='frequentlyasked',
            name='content',
            field=models.ManyToManyField(related_name='freq', to='content.contentfreq'),
        ),
    ]
