# Generated by Django 5.0.6 on 2024-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_card_description_remove_card_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ManyToManyField(related_name='sliders', to='content.imageslider'),
        ),
    ]
