# Generated by Django 5.0.6 on 2024-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_slider_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfeatures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/Features/images/%Y/%m/%d/'),
        ),
    ]
