# Generated by Django 5.0.6 on 2024-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_contentfeatures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfeatures',
            name='image',
            field=models.ImageField(default='', upload_to='files/Features/images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
